on: ["push", "pull_request", "workflow_dispatch"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build .

    - name: Run Tests and Generate Coverage Report
      run: go test -v -covermode=count -coverprofile=coverage.out

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}